// Package binlogviz proves a DROP TABLE on a real MySQL 8.0 GTID binlog exposes
// that transaction's GTID and start byte, and that mysqlbinlog --stop-position
// at that byte keeps earlier DML and excludes the DROP.
// input: internal/binlog/testdata/mysql-8.0.46-drop-table.binlog, its mysqlbinlog decode, and minimal.binlog for GTID_MODE=OFF.
// output: timeline GTID and txn start match the decode; stop-position output includes before-drop and excludes DROP TABLE.
// pos: operator I/O check for the DDL timeline identity used with mysqlbinlog and BinlogServer stop_gtid.
// note: if this file changes, update this header and module README.md.
package binlogviz

import (
	"encoding/json"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"testing"
)

func TestDropTableFixtureTimelineMatchesMysqlbinlog(t *testing.T) {
	forceEnglishRuntimeOutput(t)
	path := mustFixturePath(t, "mysql-8.0.46-drop-table.binlog")
	decodePath := strings.TrimSuffix(path, ".binlog") + ".mysqlbinlog.txt"
	stopPath := strings.TrimSuffix(path, ".binlog") + ".stop.mysqlbinlog.txt"
	decode, err := os.ReadFile(decodePath)
	if err != nil {
		t.Fatalf("read mysqlbinlog decode: %v", err)
	}
	gtid, gtidAt, queryAt := mysqlbinlogDropAnchor(t, string(decode))

	stdout, stderr, err := executeAnalyzeLikeMain(t, path, "--format", "json", "--sql-context", "full")
	if err != nil {
		t.Fatalf("analyze: %v\n%s", err, stderr)
	}
	drop := mustDropDDL(t, stdout)
	if drop.GTID != gtid || drop.TxnStartPos != gtidAt {
		t.Fatalf("timeline gtid=%q txn_start_pos=%d, mysqlbinlog gtid=%q at %d", drop.GTID, drop.TxnStartPos, gtid, gtidAt)
	}
	if drop.PositionStart != queryAt || drop.TxnStartPos == drop.PositionStart || drop.PositionEnd == gtidAt {
		t.Fatalf("txn start %d must be the GTID event, not the query [%d,%d)", drop.TxnStartPos, drop.PositionStart, drop.PositionEnd)
	}
	if drop.ServerID != 1 || drop.ThreadID == 0 {
		t.Fatalf("server/thread from the query event = %d/%d", drop.ServerID, drop.ThreadID)
	}
	if !strings.Contains(drop.MysqlbinlogStop, "--stop-position="+strconv.Itoa(gtidAt)) || drop.StopGTID != gtid {
		t.Fatalf("hints = stop %q stop_gtid %q", drop.MysqlbinlogStop, drop.StopGTID)
	}
	if _, ok := drop.raw["gtid_note"]; ok {
		t.Fatalf("gtid_note set beside a real gtid: %#v", drop.raw)
	}

	text, _, err := executeAnalyzeLikeMain(t, path, "--sql-context", "full")
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"DROP TABLE",
		"gtid=" + gtid,
		"txn start " + drop.TxnStartFile + ":" + strconv.Itoa(gtidAt),
		"mysqlbinlog --stop-position=" + strconv.Itoa(gtidAt) + " " + path,
		"BinlogServer stop_gtid=" + gtid,
		"stop before this DDL (replays earlier events, excludes this DDL)",
		"shop.orders",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("text missing %q\n%s", want, text)
		}
	}

	off, _, err := executeAnalyzeLikeMain(t, path, "--sql-context", "off", "--format", "json")
	if err != nil {
		t.Fatal(err)
	}
	offDrop := mustDropDDL(t, off)
	if offDrop.GTID != gtid || offDrop.TxnStartPos != gtidAt || offDrop.Statement != "" {
		t.Fatalf("sql-context off dropped identity or kept the statement: %+v", offDrop)
	}
	if strings.Contains(off, "generated by server") {
		t.Fatalf("sql-context off still printed the statement:\n%s", off)
	}

	md, _, err := executeAnalyzeLikeMain(t, path, "--format", "markdown")
	if err != nil {
		t.Fatal(err)
	}
	html, _, err := executeAnalyzeLikeMain(t, path, "--format", "html", "--output", "-")
	if err != nil {
		t.Fatal(err)
	}
	for name, out := range map[string]string{"markdown": md, "html": html} {
		if !strings.Contains(out, gtid) || !strings.Contains(out, "--stop-position="+strconv.Itoa(gtidAt)) {
			t.Fatalf("%s missing the DROP identity", name)
		}
	}

	assertStopPositionExcludesDrop(t, string(mustRead(t, stopPath)), gtid)
	if live, err := exec.LookPath("mysqlbinlog"); err == nil {
		full, err := exec.Command(live, "-v", "--base64-output=DECODE-ROWS", path).Output()
		if err != nil {
			t.Fatalf("mysqlbinlog: %v", err)
		}
		liveGTID, liveAt, liveQuery := mysqlbinlogDropAnchor(t, string(full))
		if liveGTID != gtid || liveAt != gtidAt || liveQuery != queryAt {
			t.Fatalf("live mysqlbinlog gtid=%q at %d query %d, checked-in gtid=%q at %d query %d", liveGTID, liveAt, liveQuery, gtid, gtidAt, queryAt)
		}
		stopped, err := exec.Command(live, "-v", "--base64-output=DECODE-ROWS", "--stop-position="+strconv.Itoa(gtidAt), path).Output()
		if err != nil {
			t.Fatalf("mysqlbinlog --stop-position: %v", err)
		}
		assertStopPositionExcludesDrop(t, string(stopped), gtid)
	}
}

func TestGTIDOffFixtureOmitsDDLGTID(t *testing.T) {
	forceEnglishRuntimeOutput(t)
	path := mustFixturePath(t, "minimal.binlog")
	stdout, stderr, err := executeAnalyzeLikeMain(t, path, "--format", "json")
	if err != nil {
		t.Fatalf("analyze minimal: %v\n%s", err, stderr)
	}
	var doc struct {
		Diagnostics struct {
			DDLEvents []map[string]any `json:"ddl_events"`
		} `json:"diagnostics"`
	}
	if err := json.Unmarshal([]byte(stdout), &doc); err != nil {
		t.Fatal(err)
	}
	if len(doc.Diagnostics.DDLEvents) == 0 {
		t.Fatal("minimal.binlog has no DDL timeline entry")
	}
	for _, event := range doc.Diagnostics.DDLEvents {
		if _, ok := event["gtid"]; ok {
			t.Fatalf("gtid field on GTID-off DDL: %#v", event)
		}
		if event["gtid_note"] != "GTID unavailable" {
			t.Fatalf("gtid_note = %#v", event["gtid_note"])
		}
		pos, _ := event["txn_start_pos"].(float64)
		stop, _ := event["mysqlbinlog_stop"].(string)
		if pos <= 0 || !strings.Contains(stop, "--stop-position=") {
			t.Fatalf("position hint missing: %#v", event)
		}
	}
	text, _, err := executeAnalyzeLikeMain(t, path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(text, "GTID unavailable") || strings.Contains(text, "gtid=") {
		t.Fatalf("text should say GTID is unavailable and not print an empty gtid:\n%s", text)
	}
	if !strings.Contains(text, "mysqlbinlog --stop-position=") {
		t.Fatalf("text missing the position hint:\n%s", text)
	}

	cmd := NewRootCommand()
	cmd.SetArgs([]string{"--lang", "zh-CN", "analyze", path})
	zh, zhErr, err := captureStdoutStderrRun(t, func() error {
		return cmd.Execute()
	})
	if err != nil {
		t.Fatalf("zh-CN analyze: %v\n%s", err, zhErr)
	}
	if !strings.Contains(zh, "GTID 不可用") || !strings.Contains(zh, "事务起点") || !strings.Contains(zh, "停在这条 DDL 之前") {
		t.Fatalf("zh-CN text:\n%s", zh)
	}
}

func assertStopPositionExcludesDrop(t *testing.T, out, dropGTID string) {
	t.Helper()
	if !strings.Contains(out, "before-drop") {
		t.Fatalf("stop-position output dropped the earlier INSERT:\n%s", out)
	}
	if strings.Contains(out, "DROP TABLE") || strings.Contains(out, "after-drop") || strings.Contains(out, dropGTID) {
		t.Fatalf("stop-position output includes the DROP transaction:\n%s", out)
	}
}

type dropDDL struct {
	GTID            string
	TxnStartFile    string
	TxnStartPos     int
	PositionStart   int
	PositionEnd     int
	ServerID        int
	ThreadID        int
	Statement       string
	MysqlbinlogStop string
	StopGTID        string
	raw             map[string]any
}

func mustDropDDL(t *testing.T, stdout string) dropDDL {
	t.Helper()
	var doc struct {
		Diagnostics struct {
			DDLEvents []map[string]any `json:"ddl_events"`
		} `json:"diagnostics"`
	}
	if err := json.Unmarshal([]byte(stdout), &doc); err != nil {
		t.Fatalf("json: %v\n%s", err, stdout)
	}
	for _, event := range doc.Diagnostics.DDLEvents {
		if event["operation"] != "DROP TABLE" {
			continue
		}
		return dropDDL{
			GTID:            strField(event, "gtid"),
			TxnStartFile:    strField(event, "txn_start_file"),
			TxnStartPos:     intField(event, "txn_start_pos"),
			PositionStart:   intField(event, "position_start"),
			PositionEnd:     intField(event, "position_end"),
			ServerID:        intField(event, "server_id"),
			ThreadID:        intField(event, "thread_id"),
			Statement:       strField(event, "statement"),
			MysqlbinlogStop: strField(event, "mysqlbinlog_stop"),
			StopGTID:        strField(event, "stop_gtid"),
			raw:             event,
		}
	}
	t.Fatalf("no DROP TABLE in %s", stdout)
	return dropDDL{}
}

func strField(event map[string]any, key string) string {
	value, _ := event[key].(string)
	return value
}

func intField(event map[string]any, key string) int {
	value, _ := event[key].(float64)
	return int(value)
}

func mustRead(t *testing.T, path string) []byte {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return data
}

// mysqlbinlogDropAnchor reads the GTID event start and the following Query
// start for the transaction whose statement contains DROP TABLE.
// "# at N" is the event start. end_log_pos on the header line is not used.
func mysqlbinlogDropAnchor(t *testing.T, dump string) (gtid string, gtidAt, queryAt int) {
	t.Helper()
	var at int
	var curGTID string
	var curAt int
	seenQueryAt := false
	for _, line := range strings.Split(dump, "\n") {
		if strings.HasPrefix(line, "# at ") {
			n, err := strconv.Atoi(strings.TrimSpace(strings.TrimPrefix(line, "# at ")))
			if err != nil {
				continue
			}
			at = n
			if curGTID != "" && !seenQueryAt && n != curAt {
				queryAt = n
				seenQueryAt = true
			}
			continue
		}
		if strings.Contains(line, "GTID_NEXT=") && !strings.Contains(line, "AUTOMATIC") {
			curGTID = quotedGTID(line)
			curAt = at
			seenQueryAt = false
			queryAt = 0
			continue
		}
		if strings.Contains(line, "DROP TABLE") && curGTID != "" && curAt > 0 && queryAt > curAt {
			return curGTID, curAt, queryAt
		}
	}
	t.Fatalf("mysqlbinlog decode has no DROP TABLE GTID anchor")
	return "", 0, 0
}

func quotedGTID(line string) string {
	start := strings.IndexByte(line, '\'')
	if start < 0 {
		return ""
	}
	rest := line[start+1:]
	end := strings.IndexByte(rest, '\'')
	if end < 0 {
		return ""
	}
	return rest[:end]
}
